// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notestore

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type AuditLog struct {
	TenantID          uuid.UUID
	ID                uuid.UUID
	ActorKind         string
	ActorMembershipID pgtype.UUID
	ActorSystem       pgtype.Text
	Action            string
	TargetID          uuid.UUID
	CreatedAt         pgtype.Timestamptz
}

type AuthToken struct {
	ID                uuid.UUID
	TokenHash         []byte
	Kind              string
	SubjectID         uuid.UUID
	CredentialVersion pgtype.Int4
	UserID            pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Invitation struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	Email       string
	AccessLevel string
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Membership struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	UserID      uuid.UUID
	AccessLevel string
	Active      bool
	CreatedAt   pgtype.Timestamptz
}

type Note struct {
	TenantID              uuid.UUID
	ID                    uuid.UUID
	Body                  string
	Version               int32
	CreatedByMembershipID uuid.UUID
}

type Temple struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Kind     string
	Name     string
}

type Tenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                uuid.UUID
	Email             string
	HashedPassword    string
	CredentialVersion int32
	EmailVerifiedAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type UserEvent struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Event     string
	CreatedAt pgtype.Timestamptz
}
