// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notestore

import (
	"context"

	"uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (tenant_id, body, created_by_membership_id)
VALUES (app_tenant_id(), $1, $2)
RETURNING id
`

type CreateNoteParams struct {
	Body                  string
	CreatedByMembershipID uuid.UUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNote, arg.Body, arg.CreatedByMembershipID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, body FROM notes WHERE tenant_id = app_tenant_id() ORDER BY body
`

type ListNotesRow struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) ListNotes(ctx context.Context) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(&i.ID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantBySlug = `-- name: TenantBySlug :one
SELECT fn_tenant_by_slug($1)::uuid AS tenant_id
`

func (q *Queries) TenantBySlug(ctx context.Context, pSlug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tenantBySlug, pSlug)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
